import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import { marked } from "marked";
import React from "react";

const styles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 56,
    paddingHorizontal: 54,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.5,
    color: "#1a1a1a",
  },
  title: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
  },
  meta: {
    fontSize: 9,
    color: "#6b7280",
    marginBottom: 20,
  },
  h1: { fontSize: 17, fontFamily: "Helvetica-Bold", marginTop: 16, marginBottom: 6 },
  h2: { fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 14, marginBottom: 5 },
  h3: { fontSize: 12, fontFamily: "Helvetica-Bold", marginTop: 10, marginBottom: 4 },
  paragraph: { marginBottom: 8, textAlign: "justify" },
  listItem: { marginBottom: 3, flexDirection: "row" },
  bullet: { width: 14, fontFamily: "Helvetica-Bold" },
  listText: { flex: 1 },
  code: {
    fontFamily: "Courier",
    fontSize: 9,
    backgroundColor: "#f3f4f6",
    padding: 8,
    marginBottom: 8,
    color: "#111827",
  },
  quote: {
    marginBottom: 8,
    paddingLeft: 10,
    borderLeftWidth: 2,
    borderLeftColor: "#d1d5db",
    color: "#374151",
    fontFamily: "Helvetica-Oblique",
  },
  hr: {
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    marginVertical: 10,
  },
  footer: {
    position: "absolute",
    bottom: 26,
    left: 54,
    right: 54,
    fontSize: 8,
    color: "#9ca3af",
    textAlign: "center",
  },
});

// Strip inline markdown so text renders cleanly (no **, `, [](), etc.).
function stripInline(md: string): string {
  return md
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 ($2)")
    .replace(/(\*\*|__)(.*?)\1/g, "$2")
    .replace(/(\*|_)(.*?)\1/g, "$2")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/~~(.*?)~~/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
}

function renderTokens(markdown: string): React.ReactNode[] {
  const tokens = marked.lexer(markdown);
  const nodes: React.ReactNode[] = [];
  let key = 0;

  for (const token of tokens) {
    const k = `t${key++}`;
    switch (token.type) {
      case "heading": {
        const style =
          token.depth <= 1 ? styles.h1 : token.depth === 2 ? styles.h2 : styles.h3;
        nodes.push(
          <Text key={k} style={style}>
            {stripInline(token.text)}
          </Text>,
        );
        break;
      }
      case "paragraph": {
        nodes.push(
          <Text key={k} style={styles.paragraph}>
            {stripInline(token.text)}
          </Text>,
        );
        break;
      }
      case "list": {
        const items = (token.items ?? []) as Array<{ text: string }>;
        items.forEach((it, i) => {
          const marker = token.ordered ? `${(token.start || 1) + i}.` : "•";
          nodes.push(
            <View key={`${k}-${i}`} style={styles.listItem}>
              <Text style={styles.bullet}>{marker}</Text>
              <Text style={styles.listText}>{stripInline(it.text)}</Text>
            </View>,
          );
        });
        break;
      }
      case "code": {
        nodes.push(
          <Text key={k} style={styles.code}>
            {token.text}
          </Text>,
        );
        break;
      }
      case "blockquote": {
        nodes.push(
          <Text key={k} style={styles.quote}>
            {stripInline(token.text ?? "")}
          </Text>,
        );
        break;
      }
      case "hr": {
        nodes.push(<View key={k} style={styles.hr} />);
        break;
      }
      default:
        break;
    }
  }
  return nodes;
}

export async function generateReportPdf(
  title: string,
  markdownContent: string,
): Promise<Buffer> {
  const generatedAt = new Date().toISOString().slice(0, 16).replace("T", " ");
  const body = renderTokens(markdownContent);

  const doc = (
    <Document title={title}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.meta}>
          Generated by MicroManus · {generatedAt} UTC
        </Text>
        {body}
        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `MicroManus deep-research report · page ${pageNumber} of ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  );

  return renderToBuffer(doc);
}
